server:
  port: 8022

spring:
  redis:
    host: 188.131.186.195
    password: yuntuzhilian
  dubbo:
    appname: hotel-provider
    registry: zookeeper://127.0.0.1:2181
swagger:
  basePackage: com.ytzl.gotrip.controller
  title: 酒店模块API接口
  description: 用户模块对外API接口